### ISSUE TITLE
Events cannot be multi-day or end at 2400 hrs

### ISSUE THREAD

**Issue by ddbruce** [rpiambulance/website#171]
When creating an event, it cannot end at 2400 hrs, and events cannot be created that span over midnight. When making an event that starts, say, at 1700 hrs and ends at 0000, the event gets added to the database:

<img width="913" alt="image" src="https://github.com/rpiambulance/website/assets/5694673/7453b829-eb19-4734-8c6e-4e305b5ddc1d">

but does not get added to gcal:

```
[Sun Feb 04 20:58:07.173069 2024] [php7:error] [pid 12374] [client 172.18.0.2:51226] PHP Fatal error:  Uncaught Google_Service_Exception: {\n "error": {\n  "errors": [\n   {\n    "domain": "calendar",\n    "reason": "timeRangeEmpty",\n    "message": "The specified time range is empty.",\n    "locationType": "parameter",\n    "location": "timeMax"\n   }\n  ],\n  "code": 400,\n  "message": "The specified time range is empty."\n }\n}\n in /var/www/html/vendor/google/apiclient/src/Google/Http/REST.php:118\nStack trace:\n#0 /var/www/html/vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\\Psr7\\Response), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#1 /var/www/html/vendor/google/apiclient/src/Google/Task/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), 'Google_Service_...')\n#2 /var/www/html/vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run()\n#3 /var/www/html/vendor/google/apiclient/src/Google/Client.php(830): Google_Http_REST::execute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7 in /var/www/html/vendor/google/apiclient/src/Google/Http/REST.php on line 118, referer: https://rpiambulance.com/
```

It is _possible_ to have a start time after an end time, but the same gcal error occurs when creation.

Ideally this gets fixed by adding a column to the database for `end_date` and/or just changing `start` and `end` to `datetime`s rather than having `date` with a start and end _time_.

**Comment by ddbruce** [comment]
Here's the schema for reference:

<img width="192" alt="image" src="https://github.com/rpiambulance/website/assets/5694673/5a105194-aa10-4503-be9d-b4ead589aea3">

**Comment by ddbruce** [comment]
`hide` seems to do nothing on the website
